### ISSUE TITLE
Add arel to projects

### ISSUE THREAD

**Issue by mdesantis** [manuelmeurer/rubydocs#11]
Hey there, 

firstly I want to say thank you for your docs, they're a must for me! 

I use arel a lot and browsing its docs on rubydocs.info is a nightmare for the latency spikes it has. Do you think is it possible to add it to the supported projects? I could even try to create a PR if you are willing to accept it.

Cheers!

**Comment by manuelmeurer** [comment]
Thanks, @mdesantis! 😄 

Arel is part of Rails AFAICS, so you should be able to find all Arel docs in the Rails docs, e.g. here: https://rubydocs.org/d/rails-6-0-3/

**Comment by mdesantis** [comment]
@manuelmeurer oh, I see... so I guess there is an hidden docs issue, that's why I can't find the Arel methods on rubydocs.org but I can on rubydoc.info. For comparison:

- https://rubydocs.org/d/rails-6-0-3/classes/Arel/SelectManager.html: shows no methods
- https://www.rubydoc.info/gems/arel/9.0.0/Arel/SelectManager: shows methods

Do you think it's fixable, or we are doomed to have silent docs? :shushing_face: :laughing:

**Comment by manuelmeurer** [comment]
Yeah, that's probably it. :(
